Milestone: Create elements and a Pop up window dynamically
kwambiee/First-Portfolio pull request #11
Opened 2022-04-07 19:20 UTC by kwambiee

# In this project, I was able to;
- Remove portfolio markup from the homepage.
- Create elements with Javascript.
- Create a pop up window with javascript.
- Style all elements with CSS.

2022-04-07 19:51 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @kwambiee👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-07 19:51 UTC, thecodechaser commented on action.js
> +              </div>
- [ ] Great on the styles but for this project you are supposed to stick to the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)design as much as possible. 
- Please place some gaps between your button's text and icon and make sure it matches the design on the template.

## Your design

![image](https://user-images.githubusercontent.com/83803414/162282541-19b5a402-92f0-453d-8efe-055dfdd3b0d1.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/162282581-76ecd8c9-d206-4221-a070-e7cdd2101564.png)

2022-04-07 19:51 UTC, thecodechaser commented on action.js
> +          </div>
- [ ] On the mobile screens the project image is not showing, Please fix the issue and make sure the image is visible on all screens. 

### See the image for reference 

![image](https://user-images.githubusercontent.com/83803414/162282995-4fda6f2c-aae8-4f51-ba9a-78d54352ad49.png)

2022-04-07 19:51 UTC, thecodechaser commented on action.js
> +      });
- [ ] Please fix the design for desktop screens. Place technologies, and buttons to the right side after the project description and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/162283537-a8cb6e6a-0125-44c9-b9e0-d3dcef884477.png)


### Figma design

![image](https://user-images.githubusercontent.com/83803414/162283582-6a22e37d-ce22-4c89-900a-2f5bb2bab98c.png)

2022-04-08 03:34 UTC, nicupop729 requested changes
# INVALID Code Review Request :stop_sign: 

Hi @kwambiee , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that is not running linter check for JavaScript.
Kindly, add linters for JS to your repo.
[Here they are](https://github.com/microverseinc/linters-config/tree/master/html-css-js);

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

2022-04-08 03:52 UTC, kwambiee commented
@nicupop729 
![Screenshot from 2022-04-08 06-50-20](https://user-images.githubusercontent.com/62090797/162359202-95799403-b1d7-42fc-a034-bd27afed51a8.png)
My linters are fine. They all show tick and no errors. I have installed the linter file for JSON.

2022-04-08 04:42 UTC, nicupop729 approved these changes
<h1>Status: Approved 🥇 ✔</h1>
Hi @kwambiee,

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

### Some highlights for you
* Correct githubflow practice ✔️ 
* Good commit messages ✔️ 
* Professional README ✔️ 
* Clean codebase ✔️ 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media3.giphy.com/media/l4HodBpDmoMA5p9bG/giphy.gif"/>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-08 04:47 UTC, merged